# Credit to Blake Hartshorn and his article here (https://www.blakehartshorn.com/monitoring-and-graphing-with-etekcity-vesync/) for the base code to use

VeSync:
  email: alikat@bu.edu
  password: 12345678

InfluxDB:
  hostname: 127.0.0.1
  port: 8086
  database: sensor_data
  username: admin
  password: influxadmin

Settings:
  interval: 10

Logging:

  version: 1
  formatters:
    simple:
      format: "%(asctime)s %(levelname)s: %(message)s"

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout

    file_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: simple
      filename: vesync.log
      maxBytes: 1048576
      backupCount: 3

  root:
    handlers: [console, file_handler]
